source "https://rubygems.org"

# Gems para  iniciar rodar o projeto
# OBS: é presiso verificar se o geckodriver esta na versão 0.15 para rodar com o 'selenium-webdriver', '3.3.0'
gem 'ffi', '1.9.14'
gem 'cucumber', '2.4.0'
gem 'capybara', '2.13.0'
gem 'selenium-webdriver', '3.3.0'
gem "chromedriver-helper"
gem 'rspec'
gem "faker"
gem "site_prism"
gem 'capybara-screenshot', '1.0.14'

